### ISSUE TITLE
Support of Conv3D

### ISSUE THREAD

**Issue by Fair95** [wzn0828/PR_Product#1]
Hi,

Firstly, thanks for the brilliant work! I just want to know if a PR product implementation of conv3d will be released?

Regards,
Fair

**Comment by wzn0828** [comment]
@Fair95  Thank you for your interest in this work. However, I'm busy with other work, so I do not have time to implement on C3d. 
I think the kernel details is similar of C2d, if you do it, welcome a pull request.

Best Regards,
